export type ColorThemeName = 'blue' | 'grad_or_purp' | 'green' | 'gr_or' | 'orange' | 'pink' | 'pink_turq' | 'turq';

export const colorThemes = {
  blue: {
    'background-image': 'linear-gradient(-0deg, #0d42b2, #0051fd)',
    'primary-color': '#003fc5',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#003fc5',
    'button-hover-gradient-end': '#003fc5',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#003fc5',
  },
  grad_or_purp: {
    'background-image': 'linear-gradient(-0deg, #9C27B0, #ffe007)',
    'primary-color': '#ff8f00',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#ff9800',
    'button-hover-gradient-end': '#ff9800',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#9227B0',
  },
  green: {
    'background-image': 'linear-gradient(-0deg, #4CAF50, #fbff07)',
    'primary-color': '#8bc34a',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#8bc34a',
    'button-hover-gradient-end': '#4CAF50',
    'button-hover-gradient-direction': '-180deg',
    'chart-circle-fill': '#4CAF50',
  },
  gr_or: {
    'background-image': ': linear-gradient(-0deg, #ff5722, #cddc39)',
    'primary-color': ': #ff8f00',
    'warn-color': ': rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': ': #ff8f00',
    'button-hover-gradient-end': ': #ff9800',
    'button-hover-gradient-direction': ': -0deg',
    'chart-circle-fill': ': #ff5722',
  },
  orange: {
    'background-image': 'linear-gradient(-0deg, #FF9800, #FFEB3B)',
    'primary-color': '#8bc34a',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#ff8f00',
    'button-hover-gradient-end': '#ff8f00',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#ff8f00',
  },
  pink: {
    'background-image': 'linear-gradient(-0deg, #00fdda,#ff0052)',
    'primary-color': '#00BCD4',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#00BCD4',
    'button-hover-gradient-end': '#00BCD4',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#ff0052',
  },
  pink_turq: {
    'background-image': 'linear-gradient(-0deg, #00fdda,#ff0052)',
    'primary-color': '#00BCD4',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#00BCD4',
    'button-hover-gradient-end': '#00BCD4',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#ff0052',
  },
  turq: {
    'background-image': 'linear-gradient(-0deg, #0db27d, #00fdda)',
    'primary-color': '#0db27d',
    'warn-color': 'rgba(255, 0, 0, 0.659)',
    'button-hover-gradient-start': '#0db27d',
    'button-hover-gradient-end': '#0db27e',
    'button-hover-gradient-direction': '-0deg',
    'chart-circle-fill': '#0db27d',
  },
};
