import { Curve } from '@zapjs/curve';
import { UserInfo } from '../store/reducers';
export declare class BondForm {
    private container;
    private endpoint;
    private providerAddress;
    private widgetID;
    private dispatch;
    private el;
    private bondDotsInput;
    private bondDotsPrice;
    private button;
    private loginPopup;
    private loginButton;
    private _dotsIssued;
    private _approved;
    private _curve;
    private _subscriber;
    private _userInfo;
    constructor(container: HTMLElement, endpoint: string, providerAddress: string, widgetID: string, dispatch: any);
    disabled: any;
    dotsIssued: any;
    curve: Curve;
    userInfo: UserInfo;
    private handleShowLogin;
    private needZapApprove;
    private handleDotsChange;
    private updateButtonTitle;
    private handleBondDotsSubmit;
    private handleApprove;
    destroy(): void;
}
